"""
email_processor – gmail integration
Generated by workflow-gen for email_processor v1.0.0
"""

from plugins.registry import plugin_registry

def register(workflow):
    """
    Register all states for the 'gmail' integration.
    """
    plugin_name = "gmail"
    plugin = plugin_registry.get_plugin(plugin_name)
    # No specific configuration provided
    config = {}
    # Register plugin states
    workflow.add_state(
        name="gmail.send_email",
        func=plugin_registry.get_state_function(
            plugin_name,
            "send_email",
            config
        )
    )
    workflow.add_state(
        name="gmail.read_emails",
        func=plugin_registry.get_state_function(
            plugin_name,
            "read_emails",
            config
        )
    )
    workflow.add_state(
        name="gmail.search_emails",
        func=plugin_registry.get_state_function(
            plugin_name,
            "search_emails",
            config
        )
    )
