"""
email_processor – slack integration
Generated by workflow-gen for email_processor v1.0.0
"""

from plugins.registry import plugin_registry

def register(workflow):
    """
    Register all states for the 'slack' integration.
    """
    plugin_name = "slack"
    plugin = plugin_registry.get_plugin(plugin_name)
    # No specific configuration provided
    config = {}
    # Register plugin states
    workflow.add_state(
        name="slack.send_message",
        func=plugin_registry.get_state_function(
            plugin_name,
            "send_message",
            config
        )
    )
    workflow.add_state(
        name="slack.read_messages",
        func=plugin_registry.get_state_function(
            plugin_name,
            "read_messages",
            config
        )
    )
    workflow.add_state(
        name="slack.upload_file",
        func=plugin_registry.get_state_function(
            plugin_name,
            "upload_file",
            config
        )
    )
    workflow.add_state(
        name="slack.create_channel",
        func=plugin_registry.get_state_function(
            plugin_name,
            "create_channel",
            config
        )
    )
